const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@Baaba Devs";
const email = "Email";
const emailHint = "yourname@gmail.com";
const password = "password";
const passwordHint = "******";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "Deep Gandhi";
const forgetPassword = "Forget Password";
const login = " Log In";
const signUp = "Sign Up";
const createNewAccount = "or, create new account";
const loginWith = "Login With";
const privacyPolicy = "Privacy Policy";
const termAndCond = "Term and Conditions";
const alreadyHaveAccount = "Already have an account?";
//Home Screen
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
